[project]
name = "rephrase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "charset-normalizer>=3.4.4",
    "lmstudio>=1.5.0",
    "pathlib>=1.0.1",
    "requests>=2.32.5",
]
